services:
    postgres:
        image: postgres
        container_name: finance-app-postgres
        environment:
            - POSTGRES_PASSWORD=finance-app@2024
            - POSTGRES_USER=postgres
            - POSTGRES_DB=financeapp
        ports:
            - "5435:5432"
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data
