name: Deploy

on:
    push:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Create .env.test file
              run: echo "DATABASE_URL="postgresql://postgres:finance_app_2024@localhost:5433/financeapp"" > .env.test

            - name: Install dependencies
              run: npm install

            - name: ESlint
              run: npm run eslint:check

            - name: Prettier
              run: npm run prettier:check

            - name: Test
              run: npm run test
